apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mongo-exporter
    name: mongo-exporter
  name: mongo-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9001
  selector:
    app: mongo-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-exporter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-exporter
      name: mongo-exporter
    spec:
      containers:
      - image: gbenhaim/mongodb_exporter
        name: mongo-exporter
        env:
        - name: MONGODB_URL
          value: "mongo-0.mongo:27017,mongo-1.mongo:27017"
        ports:
        - containerPort: 9001
          hostPort: 9001
          name: scrape
