kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 2
  template:
    metadata:
      labels:
        role: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb
          image: mongo:3.4.3
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data-volume
              mountPath: /data/db
        - name: mongodb-sidecar
          image: cvallance/mongo-k8s-sidecar:latest
          env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongodb"
          - name: KUBERNETES_MONGO_SERVICE_NAME
            value: "mongodb"
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data-volume
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
