apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mongo-exporter-0
    name: mongo-exporter-0
  name: mongo-exporter-0
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9001
  selector:
    app: mongo-exporter-0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-exporter-0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-exporter-0
      name: mongo-exporter-0
    spec:
      containers:
      - image: gbenhaim/mongodb_exporter
        name: mongo-exporter
        env:
        - name: MONGODB_URL
          value: "mongo-0.mongo:27017"
        ports:
        - containerPort: 9001
          name: scrape
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: mongo-exporter-1
    name: mongo-exporter-1
  name: mongo-exporter-1
spec:
  clusterIP: None
  ports:
  - name: scrap-1
    port: 9001
  selector:
    app: mongo-exporter-1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-exporter-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-exporter-1
      name: mongo-exporter-1
    spec:
      containers:
      - image: gbenhaim/mongodb_exporter
        name: mongo-exporter
        env:
        - name: MONGODB_URL
          value: "mongo-1.mongo:27017"
        ports:
        - containerPort: 9001
          name: scrap-1
